name: Workflow for Framework Browser UI tests

on:
  # Use cron style scheduling for running the tests at wanted intervals
  # schedule:
  #   - cron: '0 4 * * *'
  # Use workflow_dispatch to run the tests manually
  workflow_dispatch:
    inputs:
      branch:
        description: branch to run the tests on
        required: true
        default: main

env:
  JAVA_DISTRIBUTION: zulu
  JAVA_VERSION: 21
  PYTHON_VERSION: 3.11
  NODE_VERSION: 18
  ALLURE_HISTORY_COUNT: 14

jobs:  
  robot-tests:
    name: Run Robot tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}

    - name: Set up JDK for Allure report
      uses: actions/setup-java@v4
      with:
        distribution: ${{ env.JAVA_DISTRIBUTION }}
        java-version: ${{ env.JAVA_VERSION }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        architecture: 'x64'
  
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install Robot Framework
      run: |
        pip3 install virtualenv
        python3 -m venv robot_venv
        source robot_venv/bin/activate
        pip3 install -r requirements.txt
        rfbrowser init

    - name: Run Robot tests
      id: test_run
      run: |
        source robot_venv/bin/activate
        ./run_tests.sh -c

    - name: Load test report history for Allure report
      uses: actions/checkout@v4
      if: ${{ always() && steps.test_run.conclusion != 'skipped' && !cancelled() }}
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh_pages_path

    - name: Build Allure test report
      uses: simple-elf/allure-report-action@v1.8
      if: ${{ always() && steps.test_run.conclusion != 'skipped' && !cancelled() }}
      with:
        allure_results: results/allure
        gh_pages: gh_pages_path
        allure_report: allure-report
        allure_history: allure-history
        keep_reports: ${{ env.ALLURE_HISTORY_COUNT }}

    - name: Upload test results as artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with: 
        name: test-results
        path: results

    - name: Publish Allure test report to GH Pages
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ always() && steps.test_run.conclusion != 'skipped' && !cancelled() }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history
